In [1]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

In [6]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr2 = np.array((1,2,3))
print(arr2)

[1 2 3]


In [9]:
list1=  [1,2,3]
arr1 = np.array(list1)
print(list1)
print(arr1)

[1, 2, 3]
[1 2 3]


In [10]:
list2 = [1,'ab',2.0]
print(list2)

[1, 'ab', 2.0]


In [11]:
arr2 = np.array(list2)
print(arr2)

['1' 'ab' '2.0']


In [12]:
a = [[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [13]:
arr2d = np.array(a)
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [15]:
arr2d.shape

(2, 3)

In [17]:
arr.shape

(3,)

In [18]:
arr.ndim

1

In [19]:
arr2d.ndim

2

In [24]:
arr1 = np.array(15)
arr2 = np.array([15])
arr3 = np.array([[15]])
arr4 = np.array([[[15]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

()
(1,)
(1, 1)
(1, 1, 1)
