# 1차시

In [32]:
import numpy as np

In [33]:
numdata = np.loadtxt("data/NumData.csv",delimiter=",")
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [24]:
numdata.shape

(1043, 6)

In [25]:
numdata2 = numdata.reshape(6,1043) #ndarray의 형태 바꾸기 
print(numdata2)

[[ 2000.    40.   365. ...   365.  1581.  3041.]
 [12277.  2000.    40. ...    50.   365.  5350.]
 [ 6850. 15150.  1000. ...  2000.    40.   365.]
 [ 3101.  4351. 16600. ... 16600.  2000.    40.]
 [  365.  3441.  4661. ...  8450. 22250.  2000.]
 [   40.   365.  3701. ...  4601.  4601. 16600.]]


In [26]:
numdata2.shape

(6, 1043)

In [27]:
print(numdata[2,4])
print(numdata2[0,16])

3280.0
3280.0


In [28]:
print(numdata2[1,0])

12277.0


In [29]:
print(numdata[173,-1])

12277.0


In [31]:
numdata.reshape(1043,5)

ValueError: cannot reshape array of size 6258 into shape (1043,5)

In [ ]:
numdata.reshape(2,3,1043) # n개의 차원으로 변경 가능

In [ ]:
numdata3 = np.transpose(numdata)
print(numdata3)

In [ ]:
print(numdata[:,3])
print(numdata3[3,:])

In [ ]:
numdata

In [ ]:
np.delete(numdata, 1, axis=0) # 행 삭제

In [ ]:
np.delete(numdata,1,axis=1) #열 삭제

In [ ]:
np.delete(np.delete(numdata, [2,4], axis=1), (1040,1041,1042), axis=0).shape

In [ ]:
numdata

In [ ]:
numdata = np.delete(numdata,0,axis=1)

In [ ]:
numdata = np.delete(numdata, 0 ,axis=0)

In [ ]:
numdata

In [ ]:
numdata = numdata.reshape(5,1042)

In [ ]:
numdata.shape

In [ ]:
np.delete(numdata, np.arange(1040,1043), axis=0).shape#슬라이싱은 사용할 수 없음

In [ ]:
np.delete(numdata, np.arange(500,600,2), axis=0).shape

# 2차시

In [ ]:
numdata = np.loadtxt("data/NumData.csv", delimiter = ",", dtype=np.int_)

In [ ]:
np.sort(numdata) # 데이터 정렬, default axis=1 (오름차순)

In [ ]:
np.sort(numdata, axis=0)

In [ ]:
np.sort(numdata, axis=None) #전체 데이터에 대하여 오름차순 정렬

In [ ]:
-np.sort(-numdata) # 전체 데이터에 대하여 내림차순 정렬 1

In [ ]:
np.sort(numdata)[:,::-1] # 전체 데이터에 대하여 내림차순 정렬 2

In [ ]:
np.sort(numdata, axis=0)[::-1,:]

In [ ]:
np.argsort(numdata) #오름차순 정렬 후 인덱스 기억

In [ ]:
np.argsort(numdata,axis=0)[:,-1]

In [ ]:
numdata[np.argsort(numdata,axis=0)[:,-1],:]

In [ ]:
score = np.genfromtxt("data/score.csv", delimiter=",", skip_header=1, dtype=np.int_)
score

In [ ]:
np.argsort(score, axis=0)[:,2]

In [ ]:
score[np.argsort(score, axis=0)[:,2],:]

In [ ]:
np.argsort(score)

In [ ]:
np.argsort(score)[0,:]

In [ ]:
score[:,np.argsort(score)[0,:]]

In [ ]:
score

# 3차시

In [ ]:
numdata = np.genfromtxt('data/Numdata-NAN.csv',delimiter=';')
numdata

In [ ]:
np.argwhere(numdata > 1000)

In [ ]:
np.argwhere(np.isnan(numdata))

In [ ]:
for i in np.argwhere(np.isnan(numdata)):
    numdata[i[0], i[1]] = 0
numdata

In [ ]:
np.argwhere(np.isnan(numdata)) # NaN이 사라짐

In [ ]:
numdata = np.genfromtxt('data/Numdata-NAN.csv',delimiter=';')
numdata

In [ ]:
avg_col = np.nanmean(numdata,axis=0)

In [ ]:
for i in np.argwhere(np.isnan(numdata)): # NaN에 해당하는 부분을 평균으로 교체해주는 방법 BEST!!
    numdata[i[0], i[1]] = avg_col[i[1]]
numdata

In [ ]:
np.mean(numdata,axis=0) #NaN을 평균값으로 대체했기 때문에 에러 없이 평균 반환.

In [ ]:
avg_col

In [ ]:
np.random.shuffle(numdata)
numdata

In [ ]:
np.random.seed(10)
np.random.rand(2,3)

In [ ]:
np.random.seed(5) #shuffle에는 랜덤 시드가 적용되지 않음.
np.random.shuffle(numdata)
numdata

In [ ]:
numdata

In [ ]:
numdata.dtype

In [ ]:
numdata = numdata.astype(dtype=np.str_) 
numdata

In [ ]:
numdata = numdata.astype(dtype=np.float_)
numdata

In [ ]:
numdata = numdata.astype(dtype=np.int_) #str에서 float 값을 포함하고 있기 때문에 바로 int형으로 바꿀 수 없다.
numdata

In [ ]:
numdata.dtype

In [ ]:
numdata = numdata.astype(dtype = np.str_)
numdata

In [51]:
#문자열 일부 삭제
loandata = np.genfromtxt("data/Dataset_loan(2).csv",delimiter=',', dtype=np.str_, skip_header=1, usecols=[1,2,4])
loandata

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [52]:
loandata[:,0] = np.chararray.strip(loandata[:,0],'id_') #id_ 라는 문자열 삭제

In [53]:
loandata

array([['1', 'Product B', 'Location 2'],
       ['2', 'Product B', 'Location 3'],
       ['3', 'Product C', 'Location 5'],
       ...,
       ['413', 'Product B', 'Location 135'],
       ['414', 'Product C', 'Location 200'],
       ['415', 'Product A', 'Location 8']], dtype='<U12')

In [54]:
loandata[:,1] = np.chararray.strip(loandata[:,1],'Product ') #id_ 라는 문자열 삭제
loandata[:,2] = np.chararray.strip(loandata[:,2],'Location ') #id_ 라는 문자열 삭제
loandata

array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], dtype='<U12')

In [55]:
np.unique(loandata[:,1]) #중복 없이 어떤 데이터가 있는지 한눈에 확인 가능

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U12')

In [49]:
loandata[:,1] = np.where(loandata[:,1]=='A',1, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='B',2, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='C',3, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='D',4, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='E',5, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='F',6, loandata[:,1])

In [50]:
loandata = loandata.astype(np.int_)
loandata

array([[  1,   2,   2],
       [  2,   2,   3],
       [  3,   3,   5],
       ...,
       [413,   2, 135],
       [414,   3, 200],
       [415,   1,   8]])

In [ ]:
loandata.dtype

In [ ]:
loandata2 = np.genfromtxt("data/Dataset_loan(2).csv",delimiter=',',skip_header=1,usecols=[0,1,2,4,6])
loandata2

In [ ]:
loandata2.shape

In [ ]:
loandata2[:,1] = loandata[:,0]
loandata2[:,2] = loandata[:,1]
loandata2[:,3] = loandata[:,2]

In [ ]:
loandata2