# 1차시

In [2]:
import numpy as np

In [26]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [5]:
arr2 = np.array([[1],[2]])
print(arr2)
print(arr2.shape)

[[1]
 [2]]
(2, 1)


In [27]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
arr1 + arr3

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
arr2 + arr3

array([[2, 3, 4],
       [6, 7, 8]])

In [12]:
arr4 = np.array([[1,2,3]])
print(arr4)
print(arr4.shape)

[[1 2 3]]
(1, 3)


In [13]:
arr4+arr3

array([[2, 4, 6],
       [5, 7, 9]])

In [14]:
arr5 = np.array([[1],[2],[3]])
print(arr5)
print(arr5.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [16]:
arr5 + arr3

ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [21]:
arr3 + np.array([[[[[1]]]]])

array([[[[[2, 3, 4],
          [5, 6, 7]]]]])

In [30]:
np.add(arr1,arr3, dtype= np.float) # 두 행렬을 더하는 함수, 데이터 타입을 변경

C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\4294858363.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.add(arr1,arr3, dtype= np.float) # 두 행렬을 더하는 함수 (add)


array([[2., 4., 6.],
       [5., 7., 9.]])

In [34]:
np.multiply(arr1,arr3, dtype= np.float)

C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\300394897.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.multiply(arr1,arr3, dtype= np.float)


array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [35]:
np.divide(arr1,arr3)

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

# 2차시

In [57]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [39]:
arr[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
arr[1:2]

array([[ 6,  7,  8,  9, 10]])

In [44]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[1:1]

array([], shape=(0, 5), dtype=int32)

In [48]:
arr[:,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [50]:
arr[0:2 ,3:5]

array([[ 4,  5],
       [ 9, 10]])

In [52]:
arr[:2, 3:] # 맨 처음 시작 인덱스, 마지막 인덱스는 쓰지 않아도 된다.

array([[ 4,  5],
       [ 9, 10]])

In [58]:
arr[0:3:2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [59]:
arr[0:3:2, 1::3]

array([[ 2,  5],
       [12, 15]])

In [62]:
arr[::2,::3]

array([[ 1,  4],
       [11, 14]])

In [64]:
arr[::2,::-3]

array([[ 5,  2],
       [15, 12]])

In [65]:
arr[:,:] > 8

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [70]:
arr[(arr[:,:]>8) & (arr[:,:]%2==0)]

array([10, 12, 14])

In [72]:
arr[(arr[:,:]>8) | (arr[:,:]%2==0)]

array([ 2,  4,  6,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
print(arr[0])

[1 2 3 4 5]


In [75]:
print(arr[0:1])

[[1 2 3 4 5]]


In [78]:
print(arr[0:0,1:1].shape)
print(arr[0:0,1:1].ndim)

(0, 0)
2


In [81]:
print(arr[0,0])
print(arr[0,0:1])
print(arr[0:1,0:1])

1
[1]
[[1]]


In [82]:
print(arr[0,0].shape)
print(arr[0,0:1].shape)
print(arr[0:1,0:1].shape)

()
(1,)
(1, 1)


In [83]:
print(arr[0,0].ndim)
print(arr[0,0:1].ndim)
print(arr[0:1,0:1].ndim)

0
1
2


In [85]:
print(arr[0:1,0:1].squeeze())

1


In [87]:
arr[0:1,0:1].squeeze().ndim

0

In [91]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr2 = arr[0:2,1:2]
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[2]
 [7]]
(2, 1)
2


In [93]:
arr2.squeeze().shape

(2,)

In [94]:
arr2.squeeze().ndim

1

# 3차시

In [100]:
arr_empty = np.empty(shape = (2,3)) #0으로 채워주는 것이 아니라, 단순히 공간만 확보
print(arr_empty)

[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


In [101]:
arr_zero = np.zeros(shape = (2,3)) #0으로 체운 공간을 확보
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [107]:
arr_1 = np.ones(shape=(4,3), dtype=np.int)
print(arr_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\1469809908.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr_1 = np.ones(shape=(4,3), dtype=np.int)


In [113]:
arr_full = np.full(shape = (5,4), fill_value = 2)
print(arr_full)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [116]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.dtype)
print(arr)

(2, 4)
int32
[[1 2 3 4]
 [5 6 7 8]]


In [118]:
np.ones_like(arr) #ones_like : 지정한 array와 형태가 유사하지만 1로 체운 공간 반환

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [121]:
np.full_like(arr, fill_value = 2.8) #full_like : 소수점은 버리고 정수 형태로 반환

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [132]:
np.arange(3,15,3 ,dtype=np.float)

C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\3569180082.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.arange(3,15,3 ,dtype=np.float)


array([ 3.,  6.,  9., 12.])

In [134]:
np.arange(3,15,2.5).astype(np.int)

C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\830866391.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.arange(3,15,2.5).astype(np.int)


array([ 3,  5,  8, 10, 13])

In [135]:
np.random.rand()

0.4925861215272155

In [136]:
np.random.rand(2,3)

array([[0.47044383, 0.71506937, 0.41720434],
       [0.38785619, 0.63945339, 0.30432881]])

In [141]:
np.random.randint(1,10,(2,3))

array([[6, 1, 5],
       [2, 1, 9]])

In [143]:
np.random.randn(3,2) #정규분포에 의해서 발생한 난수

array([[-0.95527665, -1.09802917],
       [-0.0729494 , -0.01099015],
       [ 0.48101506,  0.21763867]])

In [156]:
np.random.seed(1) 
np.random.randint(1,10,(2,3))

array([[6, 9, 6],
       [1, 1, 2]])

In [160]:
arr = np.array([[1,2,3],[5,6,7]])
np.mean(arr,axis=1)

array([2., 6.])