# 1차시

In [2]:
import numpy as np

In [26]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [5]:
arr2 = np.array([[1],[2]])
print(arr2)
print(arr2.shape)

[[1]
 [2]]
(2, 1)


In [27]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
arr1 + arr3

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
arr2 + arr3

array([[2, 3, 4],
       [6, 7, 8]])

In [12]:
arr4 = np.array([[1,2,3]])
print(arr4)
print(arr4.shape)

[[1 2 3]]
(1, 3)


In [13]:
arr4+arr3

array([[2, 4, 6],
       [5, 7, 9]])

In [14]:
arr5 = np.array([[1],[2],[3]])
print(arr5)
print(arr5.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [16]:
arr5 + arr3

ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [21]:
arr3 + np.array([[[[[1]]]]])

array([[[[[2, 3, 4],
          [5, 6, 7]]]]])

In [30]:
np.add(arr1,arr3, dtype= np.float) # 두 행렬을 더하는 함수, 데이터 타입을 변경

C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\4294858363.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.add(arr1,arr3, dtype= np.float) # 두 행렬을 더하는 함수 (add)


array([[2., 4., 6.],
       [5., 7., 9.]])

In [34]:
np.multiply(arr1,arr3, dtype= np.float)

C:\Users\HaNbiN\AppData\Local\Temp\ipykernel_9272\300394897.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.multiply(arr1,arr3, dtype= np.float)


array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [35]:
np.divide(arr1,arr3)

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

# 2차시

In [37]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
