# 1차시

In [1]:
import numpy as np

In [58]:
numdata = np.loadtxt("data/NumData.csv",delimiter=",")
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
numdata.shape

(1043, 6)

In [7]:
numdata2 = numdata.reshape(6,1043) #ndarray의 형태 바꾸기 
print(numdata2)

[[ 2000.    40.   365. ...   365.  1581.  3041.]
 [12277.  2000.    40. ...    50.   365.  5350.]
 [ 6850. 15150.  1000. ...  2000.    40.   365.]
 [ 3101.  4351. 16600. ... 16600.  2000.    40.]
 [  365.  3441.  4661. ...  8450. 22250.  2000.]
 [   40.   365.  3701. ...  4601.  4601. 16600.]]


In [9]:
numdata2.shape

(6, 1043)

In [11]:
print(numdata[2,4])
print(numdata2[0,16])

3280.0
3280.0


In [13]:
print(numdata2[1,0])

12277.0


In [16]:
print(numdata[173,-1])

12277.0


In [20]:
numdata.reshape(1043,5)

ValueError: cannot reshape array of size 6258 into shape (1043,5)

In [23]:
numdata.reshape(2,3,1043) # n개의 차원으로 변경 가능

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]])

In [25]:
numdata3 = np.transpose(numdata)
print(numdata3)

[[ 2000.  2000.  1000. ...  2000.  1000.  2000.]
 [   40.    40.    40. ...    40.    40.    40.]
 [  365.   365.   365. ...   365.   365.   365.]
 [ 3121.  3061.  2160. ...  4201.  2080.  4601.]
 [ 4241.  4171.  3280. ...  5001.  3320.  4601.]
 [13621. 15041. 15340. ... 16600. 15600. 16600.]]


In [28]:
print(numdata[:,3])
print(numdata3[3,:])

[3121. 3061. 2160. ... 4201. 2080. 4601.]
[3121. 3061. 2160. ... 4201. 2080. 4601.]


In [30]:
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [34]:
np.delete(numdata, 1, axis=0) # 행 삭제

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [35]:
np.delete(numdata,1,axis=1) #열 삭제

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]])

In [42]:
np.delete(np.delete(numdata, [2,4], axis=1), (1040,1041,1042), axis=0).shape

(1040, 4)

In [44]:
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [47]:
numdata = np.delete(numdata,0,axis=1)

In [49]:
numdata = np.delete(numdata, 0 ,axis=0)

In [51]:
numdata

array([[   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       [   40.,   365.,  3041.,  4241., 15321.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]])

In [56]:
numdata = numdata.reshape(5,1042)

In [57]:
numdata.shape

(5, 1042)

In [61]:
np.delete(numdata, np.arange(1040,1043), axis=0).shape#슬라이싱은 사용할 수 없음

(1040, 6)

In [63]:
np.delete(numdata, np.arange(500,600,2), axis=0).shape

(993, 6)

# 2차시

In [64]:
numdata = np.loadtxt("data/NumData.csv", delimiter = ",", dtype=np.int_)

In [67]:
np.sort(numdata) # 데이터 정렬, default axis=1 (오름차순)

array([[   40,   365,  2000,  3121,  4241, 13621],
       [   40,   365,  2000,  3061,  4171, 15041],
       [   40,   365,  1000,  2160,  3280, 15340],
       ...,
       [   40,   365,  2000,  4201,  5001, 16600],
       [   40,   365,  1000,  2080,  3320, 15600],
       [   40,   365,  2000,  4601,  4601, 16600]])

In [68]:
np.sort(numdata, axis=0)

array([[ 1000,    35,   365, -2870, -2870,  -350],
       [ 1000,    35,   365, -2550, -2100,   150],
       [ 1000,    35,   365, -2450, -2000,  1100],
       ...,
       [ 9000,   125,   365, 16751, 18751, 54625],
       [ 9000,   165,   365, 17650, 20001, 54625],
       [ 9000,   165,   365, 19001, 22001, 64001]])

In [70]:
np.sort(numdata, axis=None) #전체 데이터에 대하여 오름차순 정렬

array([-2870, -2870, -2550, ..., 54625, 54625, 64001])

In [75]:
-np.sort(-numdata) # 전체 데이터에 대하여 내림차순 정렬 1

array([[13621,  4241,  3121,  2000,   365,    40],
       [15041,  4171,  3061,  2000,   365,    40],
       [15340,  3280,  2160,  1000,   365,    40],
       ...,
       [16600,  5001,  4201,  2000,   365,    40],
       [15600,  3320,  2080,  1000,   365,    40],
       [16600,  4601,  4601,  2000,   365,    40]])

In [78]:
np.sort(numdata)[:,::-1] # 전체 데이터에 대하여 내림차순 정렬 2

array([[13621,  4241,  3121,  2000,   365,    40],
       [15041,  4171,  3061,  2000,   365,    40],
       [15340,  3280,  2160,  1000,   365,    40],
       ...,
       [16600,  5001,  4201,  2000,   365,    40],
       [15600,  3320,  2080,  1000,   365,    40],
       [16600,  4601,  4601,  2000,   365,    40]])

In [79]:
np.sort(numdata, axis=0)[::-1,:]

array([[ 9000,   165,   365, 19001, 22001, 64001],
       [ 9000,   165,   365, 17650, 20001, 54625],
       [ 9000,   125,   365, 16751, 18751, 54625],
       ...,
       [ 1000,    35,   365, -2450, -2000,  1100],
       [ 1000,    35,   365, -2550, -2100,   150],
       [ 1000,    35,   365, -2870, -2870,  -350]])

In [81]:
np.argsort(numdata) #오름차순 정렬 후 인덱스 기억

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]], dtype=int64)

In [82]:
np.argsort(numdata,axis=0)[:,-1]

array([482, 493, 166, ..., 568, 534,  27], dtype=int64)

In [85]:
numdata[np.argsort(numdata,axis=0)[:,-1],:]

array([[ 1000,    50,   365,  -350,  -350,  -350],
       [ 1000,    50,   365,   150,   150,   150],
       [ 1000,    50,   365, -2550, -2100,  1100],
       ...,
       [ 9000,   125,   365, 16751, 16751, 54625],
       [ 9000,   125,   365, 15001, 17225, 54625],
       [ 9000,   165,   365, 14501, 16846, 64001]])

In [91]:
score = np.genfromtxt("data/score.csv", delimiter=",", skip_header=1, dtype=np.int_)
score

array([[  1,  96,  81,  75, 252],
       [  2,  79,  98,  89, 266],
       [  3,  95,  87,  83, 265],
       [  4,  86,  85,  76, 247],
       [  5,  82,  98, 100, 280],
       [  6,  82,  83,  79, 244],
       [  7,  93,  94,  79, 266],
       [  8,  98,  80,  95, 273]])

In [97]:
np.argsort(score, axis=0)[:,2]

array([7, 0, 5, 3, 2, 6, 1, 4], dtype=int64)

In [101]:
score[np.argsort(score, axis=0)[:,2],:]

array([[  8,  98,  80,  95, 273],
       [  1,  96,  81,  75, 252],
       [  6,  82,  83,  79, 244],
       [  4,  86,  85,  76, 247],
       [  3,  95,  87,  83, 265],
       [  7,  93,  94,  79, 266],
       [  2,  79,  98,  89, 266],
       [  5,  82,  98, 100, 280]])

In [103]:
np.argsort(score)

array([[0, 3, 2, 1, 4],
       [0, 1, 3, 2, 4],
       [0, 3, 2, 1, 4],
       [0, 3, 2, 1, 4],
       [0, 1, 2, 3, 4],
       [0, 3, 1, 2, 4],
       [0, 3, 1, 2, 4],
       [0, 2, 3, 1, 4]], dtype=int64)

In [105]:
np.argsort(score)[0,:]

array([0, 3, 2, 1, 4], dtype=int64)

In [109]:
score[:,np.argsort(score)[0,:]]

array([[  1,  75,  81,  96, 252],
       [  2,  89,  98,  79, 266],
       [  3,  83,  87,  95, 265],
       [  4,  76,  85,  86, 247],
       [  5, 100,  98,  82, 280],
       [  6,  79,  83,  82, 244],
       [  7,  79,  94,  93, 266],
       [  8,  95,  80,  98, 273]])

In [110]:
score

array([[  1,  96,  81,  75, 252],
       [  2,  79,  98,  89, 266],
       [  3,  95,  87,  83, 265],
       [  4,  86,  85,  76, 247],
       [  5,  82,  98, 100, 280],
       [  6,  82,  83,  79, 244],
       [  7,  93,  94,  79, 266],
       [  8,  98,  80,  95, 273]])

# 3차시

In [112]:
numdata = np.genfromtxt('data/Numdata-NAN.csv',delimiter=';')
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [113]:
np.argwhere(numdata > 1000)

array([[   0,    0],
       [   0,    3],
       [   0,    4],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]], dtype=int64)

In [114]:
np.argwhere(np.isnan(numdata))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [124]:
for i in np.argwhere(np.isnan(numdata)):
    numdata[i[0], i[1]] = 0
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [    0.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [125]:
np.argwhere(np.isnan(numdata)) # NaN이 사라짐

array([], shape=(0, 2), dtype=int64)

In [126]:
numdata = np.genfromtxt('data/Numdata-NAN.csv',delimiter=';')
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [128]:
avg_col = np.nanmean(numdata,axis=0)

In [129]:
for i in np.argwhere(np.isnan(numdata)): # NaN에 해당하는 부분을 평균으로 교체해주는 방법 BEST!!
    numdata[i[0], i[1]] = avg_col[i[1]]
numdata

array([[ 2000.        ,    40.        ,   365.        ,  3121.        ,
         4241.        , 13621.        ],
       [ 2000.        ,    40.        ,   365.        ,  3061.        ,
         4171.        , 15041.        ],
       [ 1000.        ,    40.        ,   365.        ,  2160.        ,
         3280.        , 15340.        ],
       ...,
       [ 2250.24777007,    40.        ,   365.        ,  4201.        ,
         5001.        , 16600.        ],
       [ 1000.        ,    40.        ,   365.        ,  2080.        ,
         3320.        , 15600.        ],
       [ 2000.        ,    40.        ,   365.        ,  4601.        ,
         4601.        , 16600.        ]])

In [132]:
np.mean(numdata,axis=0) #NaN을 평균값으로 대체했기 때문에 에러 없이 평균 반환.

array([ 2250.24777007,    46.10552764,   365.        ,  3895.99286442,
        5160.75124378, 16571.43657817])

In [134]:
avg_col

array([ 2250.24777007,    46.10552764,   365.        ,  3895.99286442,
        5160.75124378, 16571.43657817])

In [143]:
np.random.shuffle(numdata)
numdata

array([[ 2000.,    50.,   365.,  1951.,  3251., 17351.],
       [ 2000.,    50.,   365.,  6251.,  6251., 20250.],
       [ 1000.,    40.,   365.,  2150.,  3410., 15600.],
       ...,
       [ 4000.,    50.,   365.,  6300.,  8000., 22250.],
       [ 2000.,    50.,   365.,  6251.,  7751., 20250.],
       [ 2000.,    40.,   365.,  2241.,  2601.,  8171.]])

In [150]:
np.random.seed(10)
np.random.rand(2,3)

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

In [161]:
np.random.seed(5) #shuffle에는 랜덤 시드가 적용되지 않음.
np.random.shuffle(numdata)
numdata

array([[ 2000.        ,    40.        ,   365.        ,  3201.        ,
         4401.        , 14001.        ],
       [ 2250.24777007,    40.        ,   365.        ,  3121.        ,
         4501.        , 16381.        ],
       [ 1000.        ,    40.        ,   365.        ,  2200.        ,
         4600.        , 15600.        ],
       ...,
       [ 1000.        ,    40.        ,   365.        ,  2800.        ,
         3600.        , 15600.        ],
       [ 2000.        ,    50.        ,   365.        ,  3521.        ,
         5160.75124378, 16571.43657817],
       [ 2000.        ,    40.        ,   365.        ,  3400.        ,
         4600.        , 15310.        ]])

In [163]:
numdata

array([[ 2000.        ,    40.        ,   365.        ,  3201.        ,
         4401.        , 14001.        ],
       [ 2250.24777007,    40.        ,   365.        ,  3121.        ,
         4501.        , 16381.        ],
       [ 1000.        ,    40.        ,   365.        ,  2200.        ,
         4600.        , 15600.        ],
       ...,
       [ 1000.        ,    40.        ,   365.        ,  2800.        ,
         3600.        , 15600.        ],
       [ 2000.        ,    50.        ,   365.        ,  3521.        ,
         5160.75124378, 16571.43657817],
       [ 2000.        ,    40.        ,   365.        ,  3400.        ,
         4600.        , 15310.        ]])

In [165]:
numdata.dtype

dtype('float64')

In [171]:
numdata = numdata.astype(dtype=np.str_) 
numdata

array([['2000.0', '40.0', '365.0', '3201.0', '4401.0', '14001.0'],
       ['2250.2477700693757', '40.0', '365.0', '3121.0', '4501.0',
        '16381.0'],
       ['1000.0', '40.0', '365.0', '2200.0', '4600.0', '15600.0'],
       ...,
       ['1000.0', '40.0', '365.0', '2800.0', '3600.0', '15600.0'],
       ['2000.0', '50.0', '365.0', '3521.0', '5160.751243781095',
        '16571.43657817109'],
       ['2000.0', '40.0', '365.0', '3400.0', '4600.0', '15310.0']],
      dtype='<U32')

In [173]:
numdata = numdata.astype(dtype=np.float_)
numdata

array([[ 2000.        ,    40.        ,   365.        ,  3201.        ,
         4401.        , 14001.        ],
       [ 2250.24777007,    40.        ,   365.        ,  3121.        ,
         4501.        , 16381.        ],
       [ 1000.        ,    40.        ,   365.        ,  2200.        ,
         4600.        , 15600.        ],
       ...,
       [ 1000.        ,    40.        ,   365.        ,  2800.        ,
         3600.        , 15600.        ],
       [ 2000.        ,    50.        ,   365.        ,  3521.        ,
         5160.75124378, 16571.43657817],
       [ 2000.        ,    40.        ,   365.        ,  3400.        ,
         4600.        , 15310.        ]])

In [174]:
numdata = numdata.astype(dtype=np.int_) #str에서 float 값을 포함하고 있기 때문에 바로 int형으로 바꿀 수 없다.
numdata

array([[ 2000,    40,   365,  3201,  4401, 14001],
       [ 2250,    40,   365,  3121,  4501, 16381],
       [ 1000,    40,   365,  2200,  4600, 15600],
       ...,
       [ 1000,    40,   365,  2800,  3600, 15600],
       [ 2000,    50,   365,  3521,  5160, 16571],
       [ 2000,    40,   365,  3400,  4600, 15310]])

In [175]:
numdata.dtype

dtype('int32')

In [176]:
numdata = numdata.astype(dtype = np.str_)
numdata

array([['2000', '40', '365', '3201', '4401', '14001'],
       ['2250', '40', '365', '3121', '4501', '16381'],
       ['1000', '40', '365', '2200', '4600', '15600'],
       ...,
       ['1000', '40', '365', '2800', '3600', '15600'],
       ['2000', '50', '365', '3521', '5160', '16571'],
       ['2000', '40', '365', '3400', '4600', '15310']], dtype='<U11')

In [178]:
#문자열 일부 삭제
loandata = np.genfromtxt("data/Dataset_loan(2).csv",delimiter=',', dtype=np.str_, skip_header=1, usecols=[1,2,4])
loandata

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [180]:
loandata[:,0] = np.chararray.strip(loandata[:,0],'id_') #id_ 라는 문자열 삭제

In [181]:
loandata

array([['1', 'Product B', 'Location 2'],
       ['2', 'Product B', 'Location 3'],
       ['3', 'Product C', 'Location 5'],
       ...,
       ['413', 'Product B', 'Location 135'],
       ['414', 'Product C', 'Location 200'],
       ['415', 'Product A', 'Location 8']], dtype='<U12')

In [184]:
loandata[:,1] = np.chararray.strip(loandata[:,1],'Product ') #id_ 라는 문자열 삭제
loandata[:,2] = np.chararray.strip(loandata[:,2],'Location ') #id_ 라는 문자열 삭제
loandata

array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], dtype='<U12')

In [186]:
np.unique(loandata[:,1]) #중복 없이 어떤 데이터가 있는지 한눈에 확인 가능

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U12')

In [190]:
loandata[:,1] = np.where(loandata[:,1]=='A',1, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='B',2, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='C',3, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='D',4, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='E',5, loandata[:,1])
loandata[:,1] = np.where(loandata[:,1]=='F',6, loandata[:,1])

In [193]:
loandata = loandata.astype(np.int_)
loandata

array([[  1,   2,   2],
       [  2,   2,   3],
       [  3,   3,   5],
       ...,
       [413,   2, 135],
       [414,   3, 200],
       [415,   1,   8]])

In [196]:
loandata.dtype

dtype('int32')

In [199]:
loandata2 = np.genfromtxt("data/Dataset_loan(2).csv",delimiter=',',skip_header=1,usecols=[0,1,2,4,6])
loandata2

array([[1.000e+00,       nan,       nan,       nan, 1.660e+04],
       [2.000e+00,       nan,       nan,       nan, 1.660e+04],
       [3.000e+00,       nan,       nan,       nan, 1.560e+04],
       ...,
       [4.130e+02,       nan,       nan,       nan, 1.660e+04],
       [4.140e+02,       nan,       nan,       nan, 1.560e+04],
       [4.150e+02,       nan,       nan,       nan, 2.225e+04]])

In [200]:
loandata2.shape

(415, 5)

In [205]:
loandata2[:,1] = loandata[:,0]
loandata2[:,2] = loandata[:,1]
loandata2[:,3] = loandata[:,2]

In [206]:
loandata2

array([[1.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 1.660e+04],
       [2.000e+00, 2.000e+00, 2.000e+00, 3.000e+00, 1.660e+04],
       [3.000e+00, 3.000e+00, 3.000e+00, 5.000e+00, 1.560e+04],
       ...,
       [4.130e+02, 4.130e+02, 2.000e+00, 1.350e+02, 1.660e+04],
       [4.140e+02, 4.140e+02, 3.000e+00, 2.000e+02, 1.560e+04],
       [4.150e+02, 4.150e+02, 1.000e+00, 8.000e+00, 2.225e+04]])