# 1차시

In [1]:
import numpy as np

In [4]:
numdata = np.loadtxt("data/NumData.csv", delimiter = ',')
print(numdata)
print(type(numdata))

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]
<class 'numpy.ndarray'>


In [5]:
print(numdata.ndim)
print(numdata.shape)

2
(1043, 6)


In [10]:
numdata2 = np.loadtxt("data/NumData-NAN.csv", delimiter = ';')
print(numdata2)

ValueError: could not convert string to float: ''

In [12]:
numdata2 = np.genfromtxt("data/NumData-NAN.csv", delimiter = ";") #데이터에 결측값, 즉 공백이 있을 때도 데이터 로드 가능
print(numdata2)
print(numdata2.shape)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]
(1043, 6)


In [15]:
numdata3 = np.genfromtxt("data/NumData-NAN.csv", delimiter = ";", skip_header = 2, skip_footer = 2)
numdata3

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [18]:
numdata4 = np.genfromtxt("data/Numdata-NAN.csv",delimiter = ";", usecols=[0,2,5])
print(numdata4)
print(numdata4.shape)

[[ 2000.   365. 13621.]
 [ 2000.   365. 15041.]
 [ 1000.   365. 15340.]
 ...
 [   nan   365. 16600.]
 [ 1000.   365. 15600.]
 [ 2000.   365. 16600.]]
(1043, 3)


In [20]:
numdata5 = np.genfromtxt("data/Numdata-NAN.csv",delimiter = ";", usecols=[5,2,0])
print(numdata5)
print(numdata5.shape)

[[13621. 15041. 15340. ... 16600. 15600. 16600.]
 [  365.   365.   365. ...   365.   365.   365.]
 [ 2000.  2000.  1000. ...    nan  1000.  2000.]]
(3, 1043)


In [23]:
numarr5, numarr2, numarr0= np.genfromtxt("data/Numdata-NAN.csv",delimiter = ";", usecols=[5,2,0], unpack=True)
# unpack된 값과 반환받을 변수 개수를 맞춰 주어야 한다.
print(numarr5)
print(numarr2)
print(numarr0)

[13621. 15041. 15340. ... 16600. 15600. 16600.]
[365. 365. 365. ... 365. 365. 365.]
[2000. 2000. 1000. ...   nan 1000. 2000.]


In [30]:
loan_data1 = np.genfromtxt("data/Dataset_loan.csv", delimiter = ",", dtype=np.str_)
print(loan_data1)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [33]:
loan_data1[1,0] + loan_data1[2,0]

'12'

In [37]:
loan_data4 = np.genfromtxt("data/Dataset_loan.csv",delimiter = ",",dtype=(np.int_, np.str_,np.str_, np.str_, np.str_,np.float_))
print(loan_data4) 
# dtype은 하나의 타입만 가지는 것이 좋다.

[(  -1, '', '', '', '', nan) (   1, '', '', '', '', nan)
 (   2, '', '', '', '', nan) ... (1041, '', '', '', '', nan)
 (1042, '', '', '', '', nan) (1043, '', '', '', '', nan)]


In [39]:
loan_data4.shape

(1044,)

In [42]:
np.genfromtxt("data/Dataset_loan.csv", delimiter = ",", skip_header=1, usecols = [0,6]).dtype

dtype('float64')

# 2차시

In [43]:
arr = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
print(arr)

[[1 0 0 3 1]
 [3 6 6 2 9]
 [4 5 3 8 0]]


In [46]:
np.min(arr)

0

In [47]:
np.max(arr)

9

In [48]:
np.min(arr, axis=0) #열

array([1, 0, 0, 2, 0])

In [49]:
np.min(arr, axis=1) #행

array([0, 2, 0])

In [51]:
np.max(arr, axis=0)

array([4, 6, 6, 8, 9])

In [52]:
np.mean(arr)

3.4

In [53]:
np.mean(arr, axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [54]:
np.mean(arr, axis=1)

array([1. , 5.2, 4. ])

In [56]:
np.sum(arr, axis=0)

array([ 8, 11,  9, 13, 10])

In [57]:
np.sum(arr, axis=1)

array([ 5, 26, 20])

In [59]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1]) #두개의 리스트의 인덱스를 비교하여 작은것 추출

np.minimum(arr1, arr2)

array([1, 2, 3, 2, 1])

In [61]:
np.ptp(arr, axis=0) # 최대값 - 최소값 받환

array([3, 6, 6, 6, 9])

In [62]:
np.ptp(arr ,axis=1)

array([3, 7, 8])

In [64]:
np.percentile(arr, 70) # 데이터 오름차순 정렬 후, 반환할 백분위 만큼 출력

4.799999999999999

In [66]:
np.percentile(arr,70,interpolation = "higher")

5

In [67]:
np.quantile(arr,0.7,interpolation ='midpoint')

4.5

In [68]:
arr

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [69]:
np.median(arr,axis=0) #열을 기준으로 중앙값 출력

array([3., 5., 3., 3., 1.])

In [72]:
np.var(arr,axis=1) 

array([1.2 , 6.16, 6.8 ])

In [73]:
np.sqrt(np.var(arr,axis=1)) #결과값에 루트를 씌워 반환

array([1.09544512, 2.48193473, 2.60768096])

In [74]:
arr = np.array([[1,0,0,3,1],[3,6,np.nan,2,9],[4,5,3,8,0]])
print(arr)

[[ 1.  0.  0.  3.  1.]
 [ 3.  6. nan  2.  9.]
 [ 4.  5.  3.  8.  0.]]


In [77]:
np.nanmean(arr)

3.2142857142857144

In [79]:
np.nanmean(arr,axis=0)

array([2.66666667, 3.66666667, 1.5       , 4.33333333, 3.33333333])

In [80]:
np.nanstd(arr,axis=0)

array([1.24721913, 2.62466929, 1.5       , 2.62466929, 4.02768199])

In [81]:
arr = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
print(arr)

[[1 0 0 3 1]
 [3 6 6 2 9]
 [4 5 3 8 0]]


In [83]:
np.corrcoef(arr) # 행 벡터간의 상관계수(-1~1) 출력 (1에 가까울수록 상관계수 값이 높다.)

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])

# 3차시

In [84]:
np.loadtxt("data/NumData-NAN.csv",deilimiter=";")

TypeError: loadtxt() got an unexpected keyword argument 'deilimiter'

In [86]:
numdata = np.genfromtxt("data/NumData-NAN.csv",delimiter =';')
print(numdata)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [87]:
np.isnan(numdata) #결측치를 확인

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [91]:
np.sum(np.isnan(numdata), axis=0)

array([34, 48, 52, 62, 38, 26])