# 1차시

In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2 = np.array([[13,14,15,16],[17,18,19,20]])
arr3 = np.array([[13,14,15],[16,17,18],[19,20,21]])

In [7]:
print(arr1)
print(arr1.shape)
print()
print(arr2)
print(arr2.shape)
print()
print(arr3)
print(arr3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[[13 14 15 16]
 [17 18 19 20]]
(2, 4)

[[13 14 15]
 [16 17 18]
 [19 20 21]]
(3, 3)


In [12]:
np.vstack([arr1,arr2]) #vstack : 상, 하로 연결

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
np.hstack([arr1,arr3]) #hstack : 좌, 우로 연결

array([[ 1,  2,  3,  4, 13, 14, 15],
       [ 5,  6,  7,  8, 16, 17, 18],
       [ 9, 10, 11, 12, 19, 20, 21]])

In [14]:
arr4 = np.array([[13,14,15,16],[17,18,19,20],[21,22,23,24]])
arr4.shape

(3, 4)

In [20]:
arr1.shape

(3, 4)

In [22]:
np.stack([arr1,arr4], axis=0) #stack : 한 차원을 증가시켜 결합

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [24]:
arr_stack0 = np.stack([arr1,arr4], axis=0)
arr_stack0.shape

(2, 3, 4)

In [26]:
arr_stack0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [27]:
arr_stack0[1,:,:]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [30]:
arr_stack1 = np.stack([arr1,arr4], axis=1)
arr_stack1.shape

(3, 2, 4)

In [31]:
arr_stack1[:,0,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr_stack1[:,1,:]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [34]:
arr_stack2 = np.stack([arr1,arr4], axis=2)
arr_stack2.shape

(3, 4, 2)

In [36]:
arr_stack2[:,:,0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr_stack2[:,:,1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [38]:
arr1d_1 = np.array([1,2,3,4])
arr1d_2 = np.array([5,6,7,8])

In [39]:
np.concatenate([arr1d_1, arr1d_2]) # 1d array의 경우 hstack과 동일하게 결합

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.concatenate([arr1,arr2], axis=0) # 2d array의 경우 vstack과 동일하게 결합

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
temp1 = np.array([1,2,3])
temp2 = np.array([4,5,6])
np.concatenate((temp1,temp2),axis=0)

array([1, 2, 3, 4, 5, 6])

# 2차시

In [47]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

matA = np.array([[1,2],[3,4]])
matB = np.array([[5,6],[7,8]])
matC = np.array([[1,2,3],[4,5,6]])

In [50]:
v1 + v2

array([5, 7, 9])

In [51]:
v1- v2

array([-3, -3, -3])

In [52]:
2 * v1

array([2, 4, 6])

In [53]:
matA + matB

array([[ 6,  8],
       [10, 12]])

In [54]:
3 * matA

array([[ 3,  6],
       [ 9, 12]])

In [55]:
v1 * v2 # 각 요소별 연산

array([ 4, 10, 18])

In [57]:
np.inner(v1,v2) # 동일한 차원의 벡터의 내접(각 요소별 곱셈의 합) 구하기

32

In [58]:
matA * matB

array([[ 5, 12],
       [21, 32]])

In [64]:
np.matmul(matA,matB) # 행렬의 곱

array([[19, 22],
       [43, 50]])

In [66]:
matA @ matB # 행렬의 곱

array([[19, 22],
       [43, 50]])

In [68]:
np.matmul(matA,matC)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [69]:
np.matmul(matC,matA) #행과 열의 개수가 맞지 않으면 계산안됨

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [70]:
np.linalg.inv(matA #역행렬 구하기

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [72]:
np.matmul(matA, np.linalg.inv(matA))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [73]:
np.linalg.pinv(matC)

array([[-0.94444444,  0.44444444],
       [-0.11111111,  0.11111111],
       [ 0.72222222, -0.22222222]])

In [74]:
np.linalg.det(matA)

-2.0000000000000004

In [75]:
np.linalg.det(matB)

-2.000000000000005

In [77]:
eig_val, eig_vec = np.linalg.eig(matA) #고유값과 고유 벡터

In [78]:
print(eig_val)
print(eig_vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [80]:
np.matmul(matA,eig_vec[:,0])

array([ 0.30697009, -0.21062466])

In [82]:
eig_val[0] * eig_vec[:,0]

array([ 0.30697009, -0.21062466])

In [83]:
np.matmul(matA,eig_vec[:,1])

array([-2.23472698, -4.88542751])

In [84]:
eig_val[1] * eig_vec[:,1]

array([-2.23472698, -4.88542751])

In [85]:
np.trace(matA) #대각선분의 합

5

In [87]:
np.transpose(matA) # == arr.T
matA.T # == np.transpose

array([[1, 3],
       [2, 4]])

In [88]:
np.diag([2,3,4]) #대각선분이 2,3,4이고, 나머지가 모두 0인 정방행렬 생성

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [90]:
np.diag([1,5])

array([[1, 0],
       [0, 5]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.trace(np.eye(10))

10.0

# 3차시

In [93]:
import pandas as pd

In [94]:
pd.__version__

'1.4.2'

In [95]:
sr = ['coffee',100,5.5,False,'민규']
print(sr)

['coffee', 100, 5.5, False, '민규']


In [96]:
s1 = pd.Series(sr) #인덱스와 
print(s1)

0    coffee
1       100
2       5.5
3     False
4        민규
dtype: object


In [97]:
dic={"Dog":'mammal',"Rose":'Flower','Pine':'Tree',"Snake":'reptile'}
s2 = pd.Series(dic) 
print(s2)

Dog       mammal
Rose      Flower
Pine        Tree
Snake    reptile
dtype: object


In [99]:
type(s2.index)

pandas.core.indexes.base.Index

In [100]:
s2.index #인덱스 구성 요소 반환

Index(['Dog', 'Rose', 'Pine', 'Snake'], dtype='object')

In [101]:
s2.values #값 반환

array(['mammal', 'Flower', 'Tree', 'reptile'], dtype=object)

In [103]:
type(s2.values)

numpy.ndarray

In [102]:
s1.values

array(['coffee', 100, 5.5, False, '민규'], dtype=object)

In [105]:
type(s1.values)

numpy.ndarray

In [106]:
s2.dtype

dtype('O')

In [107]:
s1.dtype #Object형으로 나타남

dtype('O')

In [108]:
s3 = pd.Series([10,20,30,40,50])
print(s3)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [109]:
s3.sum() #합계반환

150

In [110]:
s3.mean() #평균반환

30.0

In [111]:
s3.product() #요소별 곱 반환

12000000

In [112]:
fruits = ['apple','melon','banana','grapes']
weekdays = ['mon','tue','wed','thu']
s4 = pd.Series(data = fruits, index = weekdays) #key, value 따로 적용 가능
print(s4)

mon     apple
tue     melon
wed    banana
thu    grapes
dtype: object


In [114]:
s4 = pd.Series(data = fruits, index = weekdays, name = 'fruit')
print(s4)

mon     apple
tue     melon
wed    banana
thu    grapes
Name: fruit, dtype: object


In [115]:
len(s4) #value or index count

4

In [116]:
type(s4)

pandas.core.series.Series

In [117]:
dir(s3) #해당 Series에서 사용할 수 있는 메소드, 클래스

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__redu

In [122]:
sorted(s4)

['apple', 'banana', 'grapes', 'melon']

In [123]:
sorted(s3)

[10, 20, 30, 40, 50]

In [124]:
dict(s4) #Series를 Dictionary 형태로 변환

{'mon': 'apple', 'tue': 'melon', 'wed': 'banana', 'thu': 'grapes'}

In [125]:
min(s4)

'apple'

In [126]:
max(s3)

50

In [127]:
s3.is_unique #속한 데이터값에 중복이 없는지 확인

True

In [128]:
s5 = pd.Series([10,10,20,30])
s5.is_unique

False

In [129]:
s4.ndim #Series는 1차원이므로 ndim을 확인할 필요 없음

1

In [130]:
s4.shape 

(4,)

In [131]:
s4.size #전체 데이터(values)의 수

4

In [132]:
s4.name # Series의 이름 출력

'fruit'