### ※ Importing the Packages

In [88]:
import numpy as np

In [90]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

###1.Importing the Data

In [292]:
# 1. Issue_d, loan_status, term, grade, sub_grade, verification_status, url, addr_state 열만 추출함
data_str = np.genfromtxt("data/project.csv",delimiter=',',dtype='str_', skip_header=1, usecols=[1,3,5,7,8,9,10,11])
data_str


array([['15-May', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['15-Sep', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['15-Jun', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['15-Apr', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['15-Dec', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### 2.Issue Date

In [293]:
# np.unique를 사용하여 Issue_d 데이터 종류 확인
np.unique(data_str[:,0])

array(['', '15-Apr', '15-Aug', '15-Dec', '15-Feb', '15-Jan', '15-Jul', '15-Jun', '15-Mar',
       '15-May', '15-Nov', '15-Oct', '15-Sep'], dtype='<U69')

In [294]:
# '15-' 삭제
data_str[:,0] = np.chararray.strip(data_str[:,0],'15-')
data_str[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [267]:
# 삭제 후, Issue_d 데이터 종류 확인
np.unique(data_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [199]:
# month ndarray
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [295]:
# 위 months ndarray의 각 값을 index 값으로 변경
# ex> 비어있는 경우 → 0, 'Jan' → 1, Feb → 2,  .... , Nov → 11, Dec → 12

for i in range(13):
  # months[0] = '', months[1] = 'Jan', months[2] = 'Feb'...., months[12] = 'Dec'
  # data_str[:,0]의 값이 months[i]와 동일할 경우, 해당 값을 i로 변경
  # np.where 이용
  data_str[:,0] = np.where(data_str[:,0]==months[i].astype('str_'),i,0)

In [296]:
# 완료 후, Issue_d 데이터 종류 확인
np.unique(data_str[:,0])

array(['0'], dtype='<U69')

### 3. Loan Status

In [297]:
# np.unique를 사용하여 loan_status 데이터 종류 확인
np.unique(data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [271]:
# status_bad ndarray
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [298]:
# data_str[:,1](loan_status)의 값이 status_bad에 포함된 경우 0, 아닐 경우 1로 데이터 값 변경
# np.where와 np.isin 사용
# ex> np.isin(ndarray, list) → ndarray의 값이 list에 포함된 경우 True, 포함되지 않은 경우 False
data_str[:,1] = np.where(np.isin(data_str[:,1],status_bad),0,1)

In [299]:
# 완료 후, Issue_d 데이터 종류 확인
np.unique(data_str[:,1])

array(['0', '1'], dtype='<U69')

### 4. Term

In [362]:
# np.unique를 사용하여 term 데이터 종류 확인
np.unique(data_str[:,2])

array(['', ' 36 ', ' 60 '], dtype='<U69')

In [369]:
# months 삭제
data_str[:,2] = np.chararray.strip(data_str[:,2],'months')
data_str[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [368]:
# 비어 있는 경우(''), '60'으로 대체
data_str[:,2] = np.where(data_str[:,2]=='','60',data_str[:,2])

In [367]:
# 완료 후, term 데이터 종류 확인
np.unique(data_str[:,2])

array(['36', '60'], dtype='<U69')

### 5. Grade and Subgrade

In [300]:
# np.unique를 사용하여 grade 데이터 종류 확인
np.unique(data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [301]:
# np.unique를 사용하여 sub_grade 데이터 종류 확인
np.unique(data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### 5-1.sub_grade 비어 있는 값 채우기

In [311]:
# sub_grade열의 값이 비어있고, grade열의 값이 있을 경우, grade의 값으로 sub_grade열을 채움

grade = ['A','B','C','D','E','F','G']

for i in grade:
    data_str[:,4] = np.where((data_str[:,4]=='') & (data_str[:,3]==i),i+'5',data_str[:,4])
  # i → 'A', 'B', 'C', .... , 'G'
  # data_str[:,4]가 존재하지 않고, data_str[:,3] 값이 'i'와 동일한 경우
  # data_str[:,4]값을 i+'5'로 변경함 (아닌 경우, 그대로 둔다.)
  # np.where 이용
  

In [312]:
# sub_grade열의 값(data_str[:,4])과 grade 값(data_str[:,3])이 모두 비어있는 경우, sub_grade열(data_str[:,4])을 'H1'으로 채움
data_str[:,4] = np.where((data_str[:,4]=='') & (data_str[:,3]==''),'H1',data_str[:,4])

In [313]:
# 완료 후, sub_grade 데이터 종류 확인
np.unique(data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### 5-2. grade열 삭제

In [317]:
# grade 열 삭제 (np.delete)
data_str = np.delete(data_str,3,axis=1)

In [321]:
data_str[:5,:]

array([['0', '1', ' 36 ', 'C3', 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', ' 36 ', 'A5', 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['0', '1', ' 36 ', 'B5', 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ['0', '1', ' 36 ', 'A5', 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=53222800', 'OH'],
       ['0', '1', ' 36 ', 'E3', 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57803010', 'TX']],
      dtype='<U69')

#### 5-3. sub_grade값 수로 변경

In [322]:
keys = list(np.unique(data_str[:,3]))                         
values = list(range(1, np.unique(data_str[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [323]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [325]:
# 위의 dict_sub_grade를 활용하여 sub_grade의 값이 dict_sub_grade의 key와 동일할 때, 해당 key의 value로 대체
for i in dict_sub_grade.keys():
    data_str[:,3] = np.where(data_str[:,3]==i,dict_sub_grade[i],data_str[:,3])
  # i → 'A1', 'A2', 'A3',....... , 'G3', 'G4', 'G5', 'H1'
  # data_str[:,3]과 i가 동일한 경우, dict_sub_grade에서 key 값이 i인 데이터로 data_str[:,3]을 변경함
  # np.where 이용, dict_sub_grade.get(i)는 dict 타입의 dict_sub_grade에서 key 값이 i인 데이터의 값을 반환
  
  

In [326]:
# 완료 후, sub_grade 데이터 종류 확인
np.unique(data_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### 6. Verification Status

In [327]:
# np.unique를 사용하여 verification_status 데이터 종류 확인
np.unique(data_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [336]:
# 값이 비어 있는 경우('')와 ‘Not Verified’는 0으로 변경, ‘Source Verified’과 ‘Verified’는 1로 변경함
# np.where 이용
data_str[:,4] = np.where((data_str[:,4]=='') | (data_str[:,4]=='Not Verified'),0,data_str[:,4])
data_str[:,4] = np.where((data_str[:,4]=='Verified') | (data_str[:,4]=='Source Verified'),1,data_str[:,4])

In [337]:
# 완료 후, verification_status 데이터 종류 확인
np.unique(data_str[:,4])

array(['0', '1'], dtype='<U69')

### 7. URL

In [338]:
# "https://www.lendingclub.com/browse/loanDetail.action?loan_id=" 삭제하고 숫자만 남김
data_str[:,5] = np.chararray.strip(data_str[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [339]:
data_str[:10,5]

array(['48010226', '57693261', '59432726', '53222800', '57803010', '63398019', '60850626',
       '46816139', '63918356', '63651616'], dtype='<U69')

### 8. State Address

In [340]:
# np.unique를 사용하여 addr_state 데이터 종류 확인
np.unique(data_str[:,6])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [341]:
# 값이 비어 있는 경우(''), 0으로 값 변경,
data_str[:,6] = np.where(data_str[:,6]=='',0,data_str[:,6])

In [342]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [347]:
# addr_state 값(data_str[:,6]의 값)이 
# states_west에 속하는 경우 0, states_south에 속하는 경우 1, 
# states_midwest에 속하는 경우 2, states_east에 속하는 경우 3
# states_east에 속하는 경우 4로 변경
# np.where와 np.isin 이용
data_str[:,6] = np.where(np.isin(data_str[:,6],states_west),0,data_str[:,6])
data_str[:,6] = np.where(np.isin(data_str[:,6],states_south),1,data_str[:,6])
data_str[:,6] = np.where(np.isin(data_str[:,6],states_midwest),2,data_str[:,6])
data_str[:,6] = np.where(np.isin(data_str[:,6],states_east),4,data_str[:,6])

In [348]:
# 완료 후, addr_state 데이터 종류 확인
np.unique(data_str[:,6])

array(['0', '1', '2', '3'], dtype='<U69')

### 9. int로 타입 변경

In [372]:
# 모든 데이터를 np.int 타입으로 변환

data_str = data_str.astype(np.int_)
data_str

array([[       0,        1,       36, ...,        1, 48010226,        0],
       [       0,        1,       36, ...,        1, 57693261,        3],
       [       0,        1,       36, ...,        1, 59432726,        3],
       ...,
       [       0,        1,       36, ...,        1, 50415990,        0],
       [       0,        1,       36, ...,        1, 46154151,        2],
       [       0,        1,       36, ...,        0, 66055249,        2]])

### 10. 숫자로 구성된 열만 추출하여 비어 있는 값을 열의 평균으로 대체하기

In [375]:
# id, loan_amnt, funded_amnt, installment, total_pymnt 열만 추출
data_num = np.genfromtxt("data/project.csv",delimiter=',',dtype='float_', skip_header=1, usecols=[0,2,4,6,12])
data_num

array([[48010226.  ,    35000.  ,    35000.  ,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,         nan,     2185.64],
       [46154151.  ,         nan,    10000.  ,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,      309.97,      301.9 ]])

In [383]:
# 각 열의 평균 값 구하기
col_mean = np.nanmean(data_num,axis=1)
col_mean

array([ 9618172.76, 11551775.85, 11893038.14, ..., 12609543.91, 11541926.17, 13215172.17])

In [384]:
# 비어 있는 값을 해당 열의 평균값으로 대체하기
for i in range(5):
  # i → 0, 1, 2, 3, 4
  # data_num[:,i]의 값이 nan일 경우, col_mean[i]로 변경, nan이 아닐 경우, 변경하지 않음
  # np.where와 np.isnan 이용
  data_num[:,i] = np.where(np.isnan(data_num[:,i]),col_mean[i],data_num[:,i])

data_num

array([[48010226.  ,    35000.  ,    35000.  ,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 10648818.81,     2185.64],
       [46154151.  , 11551775.85,    10000.  ,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,      309.97,      301.9 ]])

In [397]:
# 위 ndarray와 9번 ndarrya 결합하기
np.hstack([data_str,data_num])

array([[       0.  ,        1.  ,       36.  , ...,    35000.  ,     1184.86,     9452.96],
       [       0.  ,        1.  ,       36.  , ...,    30000.  ,      938.57,     4679.7 ],
       [       0.  ,        1.  ,       36.  , ...,    15000.  ,      494.86,     1969.83],
       ...,
       [       0.  ,        1.  ,       36.  , ...,    10000.  , 10648818.81,     2185.64],
       [       0.  ,        1.  ,       36.  , ...,    10000.  ,      354.3 ,     3199.4 ],
       [       0.  ,        1.  ,       36.  , ...,    10000.  ,      309.97,      301.9 ]])

(10000, 5)