# 1차시

In [1]:
import numpy as np

In [58]:
numdata = np.loadtxt("data/NumData.csv",delimiter=",")
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
numdata.shape

(1043, 6)

In [7]:
numdata2 = numdata.reshape(6,1043) #ndarray의 형태 바꾸기 
print(numdata2)

[[ 2000.    40.   365. ...   365.  1581.  3041.]
 [12277.  2000.    40. ...    50.   365.  5350.]
 [ 6850. 15150.  1000. ...  2000.    40.   365.]
 [ 3101.  4351. 16600. ... 16600.  2000.    40.]
 [  365.  3441.  4661. ...  8450. 22250.  2000.]
 [   40.   365.  3701. ...  4601.  4601. 16600.]]


In [9]:
numdata2.shape

(6, 1043)

In [11]:
print(numdata[2,4])
print(numdata2[0,16])

3280.0
3280.0


In [13]:
print(numdata2[1,0])

12277.0


In [16]:
print(numdata[173,-1])

12277.0


In [20]:
numdata.reshape(1043,5)

ValueError: cannot reshape array of size 6258 into shape (1043,5)

In [23]:
numdata.reshape(2,3,1043) # n개의 차원으로 변경 가능

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]])

In [25]:
numdata3 = np.transpose(numdata)
print(numdata3)

[[ 2000.  2000.  1000. ...  2000.  1000.  2000.]
 [   40.    40.    40. ...    40.    40.    40.]
 [  365.   365.   365. ...   365.   365.   365.]
 [ 3121.  3061.  2160. ...  4201.  2080.  4601.]
 [ 4241.  4171.  3280. ...  5001.  3320.  4601.]
 [13621. 15041. 15340. ... 16600. 15600. 16600.]]


In [28]:
print(numdata[:,3])
print(numdata3[3,:])

[3121. 3061. 2160. ... 4201. 2080. 4601.]
[3121. 3061. 2160. ... 4201. 2080. 4601.]


In [30]:
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [34]:
np.delete(numdata, 1, axis=0) # 행 삭제

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [35]:
np.delete(numdata,1,axis=1) #열 삭제

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]])

In [42]:
np.delete(np.delete(numdata, [2,4], axis=1), (1040,1041,1042), axis=0).shape

(1040, 4)

In [44]:
numdata

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [47]:
numdata = np.delete(numdata,0,axis=1)

In [49]:
numdata = np.delete(numdata, 0 ,axis=0)

In [51]:
numdata

array([[   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       [   40.,   365.,  3041.,  4241., 15321.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]])

In [56]:
numdata = numdata.reshape(5,1042)

In [57]:
numdata.shape

(5, 1042)

In [61]:
np.delete(numdata, np.arange(1040,1043), axis=0).shape#슬라이싱은 사용할 수 없음

(1040, 6)

In [63]:
np.delete(numdata, np.arange(500,600,2), axis=0).shape

(993, 6)

# 2차시

In [64]:
numdata = np.loadtxt("data/NumData.csv", delimiter = ",", dtype=np.int_)

In [67]:
np.sort(numdata) # 데이터 정렬, default axis=1 (오름차순)

array([[   40,   365,  2000,  3121,  4241, 13621],
       [   40,   365,  2000,  3061,  4171, 15041],
       [   40,   365,  1000,  2160,  3280, 15340],
       ...,
       [   40,   365,  2000,  4201,  5001, 16600],
       [   40,   365,  1000,  2080,  3320, 15600],
       [   40,   365,  2000,  4601,  4601, 16600]])

In [68]:
np.sort(numdata, axis=0)

array([[ 1000,    35,   365, -2870, -2870,  -350],
       [ 1000,    35,   365, -2550, -2100,   150],
       [ 1000,    35,   365, -2450, -2000,  1100],
       ...,
       [ 9000,   125,   365, 16751, 18751, 54625],
       [ 9000,   165,   365, 17650, 20001, 54625],
       [ 9000,   165,   365, 19001, 22001, 64001]])

In [70]:
np.sort(numdata, axis=None) #전체 데이터에 대하여 오름차순 정렬

array([-2870, -2870, -2550, ..., 54625, 54625, 64001])

In [75]:
-np.sort(-numdata) # 전체 데이터에 대하여 내림차순 정렬 1

array([[13621,  4241,  3121,  2000,   365,    40],
       [15041,  4171,  3061,  2000,   365,    40],
       [15340,  3280,  2160,  1000,   365,    40],
       ...,
       [16600,  5001,  4201,  2000,   365,    40],
       [15600,  3320,  2080,  1000,   365,    40],
       [16600,  4601,  4601,  2000,   365,    40]])

In [78]:
np.sort(numdata)[:,::-1] # 전체 데이터에 대하여 내림차순 정렬 2

array([[13621,  4241,  3121,  2000,   365,    40],
       [15041,  4171,  3061,  2000,   365,    40],
       [15340,  3280,  2160,  1000,   365,    40],
       ...,
       [16600,  5001,  4201,  2000,   365,    40],
       [15600,  3320,  2080,  1000,   365,    40],
       [16600,  4601,  4601,  2000,   365,    40]])

In [79]:
np.sort(numdata, axis=0)[::-1,:]

array([[ 9000,   165,   365, 19001, 22001, 64001],
       [ 9000,   165,   365, 17650, 20001, 54625],
       [ 9000,   125,   365, 16751, 18751, 54625],
       ...,
       [ 1000,    35,   365, -2450, -2000,  1100],
       [ 1000,    35,   365, -2550, -2100,   150],
       [ 1000,    35,   365, -2870, -2870,  -350]])

In [81]:
np.argsort(numdata) #오름차순 정렬 후 인덱스 기억

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]], dtype=int64)

In [82]:
np.argsort(numdata,axis=0)[:,-1]

array([482, 493, 166, ..., 568, 534,  27], dtype=int64)

In [85]:
numdata[np.argsort(numdata,axis=0)[:,-1],:]

array([[ 1000,    50,   365,  -350,  -350,  -350],
       [ 1000,    50,   365,   150,   150,   150],
       [ 1000,    50,   365, -2550, -2100,  1100],
       ...,
       [ 9000,   125,   365, 16751, 16751, 54625],
       [ 9000,   125,   365, 15001, 17225, 54625],
       [ 9000,   165,   365, 14501, 16846, 64001]])

In [91]:
score = np.genfromtxt("data/score.csv", delimiter=",", skip_header=1, dtype=np.int_)
score

array([[  1,  96,  81,  75, 252],
       [  2,  79,  98,  89, 266],
       [  3,  95,  87,  83, 265],
       [  4,  86,  85,  76, 247],
       [  5,  82,  98, 100, 280],
       [  6,  82,  83,  79, 244],
       [  7,  93,  94,  79, 266],
       [  8,  98,  80,  95, 273]])

In [97]:
np.argsort(score, axis=0)[:,2]

array([7, 0, 5, 3, 2, 6, 1, 4], dtype=int64)

In [101]:
score[np.argsort(score, axis=0)[:,2],:]

array([[  8,  98,  80,  95, 273],
       [  1,  96,  81,  75, 252],
       [  6,  82,  83,  79, 244],
       [  4,  86,  85,  76, 247],
       [  3,  95,  87,  83, 265],
       [  7,  93,  94,  79, 266],
       [  2,  79,  98,  89, 266],
       [  5,  82,  98, 100, 280]])

In [103]:
np.argsort(score)

array([[0, 3, 2, 1, 4],
       [0, 1, 3, 2, 4],
       [0, 3, 2, 1, 4],
       [0, 3, 2, 1, 4],
       [0, 1, 2, 3, 4],
       [0, 3, 1, 2, 4],
       [0, 3, 1, 2, 4],
       [0, 2, 3, 1, 4]], dtype=int64)

In [105]:
np.argsort(score)[0,:]

array([0, 3, 2, 1, 4], dtype=int64)

In [108]:
score[:,np.argsort(score)[0,:]]

array([[  1,  75,  81,  96, 252],
       [  2,  89,  98,  79, 266],
       [  3,  83,  87,  95, 265],
       [  4,  76,  85,  86, 247],
       [  5, 100,  98,  82, 280],
       [  6,  79,  83,  82, 244],
       [  7,  79,  94,  93, 266],
       [  8,  95,  80,  98, 273]])