# 3) 기타 데이터 처리

In [108]:
!pip install pandas
!pip install numpy

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.

In [109]:
import numpy as np
import pandas as pd

In [110]:
dataset = pd.read_csv("data/Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# 3-1) X와 y분리

In [111]:
# X: country, age, salary 
# y: purchased(Yes/No) #정답 label
# -> classification: 국가, 나이, 연봉 정보를 통해 제품을 구입할지 말지 판단

#1) X와 y분리
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

print('X\n')
print(X)
print(X.shape)
print(type(X))

print('-'*100)

print('y\n')
print(y)
print(y.shape)
print(type(y))

X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0
(10, 3)
<class 'pandas.core.frame.DataFrame'>
----------------------------------------------------------------------------------------------------
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object
(10,)
<class 'pandas.core.series.Series'>


In [112]:
#dataset으로부터 ndarray로 타입으로 X와 y추출
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

#위와 동일한 방법
X = dataset.values[:,:-1]
y = dataset.values[:,-1]

y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# 3-2) 문자를 숫자로 변경

In [113]:
#원핫 인코딩 : 문자와 숫자의 각각의 특성을 반영하지 않기 위해
# 문자가 존재할 경우 1, 존재하지 않을 경우 0으로 변환
# 각 문자와 숫자간의 관계가 없음.

In [114]:
# X 1열 문자열
print(X[:,0])

['France' 'Spain' 'Germany' 'Spain' 'Germany' 'France' 'Spain' 'France'
 'Germany' 'France']


In [115]:
# unique() : 데이터프레임의 중복을 제거
print(dataset.loc[:,'Country'].unique())
print(dataset.loc[:,'Country'].nunique())

# unique() : 데이터프레임의 중복을 제거
print(dataset.iloc[:,-1].unique())
print(dataset.iloc[:,-1].nunique())

['France' 'Spain' 'Germany']
3
['No' 'Yes']
2


In [116]:
!pip install sklearn

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


In [127]:
# 문자열을 정수로 변경
from sklearn.preprocessing import LabelEncoder

#1) LabelEncoder 객체 생성
le = LabelEncoder()

#2) Label Encoder을 적용할 준비 (어떤 데이터를 적용할 것인지 미리 정보를 확인) -> 변환 X
le.fit(X[:,0]
# -> X[:,0]의 데이터를 확인하고, 어떤 문자열을 어떤 정수로 바꿀지 결정

#3) 미리 준비한 LabelEncoder 객체에 데이터를 적용하여 변환
X_le = le.transform(X[:,0])
X_le

SyntaxError: invalid syntax (2268077419.py, line 12)

In [128]:
#reshape : 데이터의 형태 변환
#기존 값의 개수는 유지하되, 열에 -1을 사용하여 자동으로 변경되게 설정 가능
X2 = X[:,0].reshape(-1,1) #2차원으로 변환

X1 = X2.reshape(-1)#2D(이상) array를 1D로 변경할 때 reshape(-1)

print(X2.shape)
print(X1.shape)

(10, 1)
(10,)


In [129]:
from sklearn.preprocessing import OneHotEncoder
# oneHotEncoding은 2D array만 적용가능
ohe = OneHotEncoder()
ohe.fit(X[:,:1])
# == ohe.fit(X[:,0].reshape(-1,1))
X_ohe_temp = ohe.transform(X[:,:1])

X_ohe = X_ohe_temp.toarray() #반환 결과를 ndarray로 반환
print(X_ohe) #OneHotEncoding 결과

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


# 3-3) 결측값(NaN)을 평균값으로 채우기 

In [130]:
from sklearn.impute import SimpleImputer

im_mean = SimpleImputer(missing_values = np.nan, strategy ='mean')
# strategy = {'mean':평균값, 'median':중앙값, 'most_frequent':가장 많이 사용된, 'constant':fill_value 파라미터로 입력한 값으로 대체}

im_mean.fit(X[:,1:])
X_im = im_mean.transform(X[:,1:])
print(X_im)

[[4.40000000e+01 7.20000000e+04]
 [2.70000000e+01 4.80000000e+04]
 [3.00000000e+01 5.40000000e+04]
 [3.80000000e+01 6.10000000e+04]
 [4.00000000e+01 6.37777778e+04]
 [3.50000000e+01 5.80000000e+04]
 [3.87777778e+01 5.20000000e+04]
 [4.80000000e+01 7.90000000e+04]
 [5.00000000e+01 8.30000000e+04]
 [3.70000000e+01 6.70000000e+04]]


# 3-4) ndarray 결합

In [131]:
X_new = np.concatenate((X_ohe, X_im),axis=1)

print(X_new)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


# 3-5) tranning data와 test data 분리

In [132]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(X_new, y, test_size=0.3, random_state=42)
# test_size : 전체 데이터에 대한 test data 비율
# random_state : 랜덤 시드 값

print(X_test)
print(y_test)

print(X_train)
print(y_train)

[[0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]]
['No' 'Yes' 'Yes']
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]]
['No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No']


# 3-5) Sacling (standardization)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [133]:
print(X_train[:,3:])
print(X_test[:,3:])

[[4.40000000e+01 7.20000000e+04]
 [4.80000000e+01 7.90000000e+04]
 [3.00000000e+01 5.40000000e+04]
 [3.70000000e+01 6.70000000e+04]
 [4.00000000e+01 6.37777778e+04]
 [3.80000000e+01 6.10000000e+04]
 [3.87777778e+01 5.20000000e+04]]
[[5.0e+01 8.3e+04]
 [2.7e+01 4.8e+04]
 [3.5e+01 5.8e+04]]


In [134]:
sc = StandardScaler()
sc.fit(X_train[:,3:])

X_train_sc = sc.transform(X_train[:,3:])
X_test_sc = sc.transform(X_test[:,3:])

print(X_train_sc)
print(X_test_sc)

[[ 0.8790543   0.8892086 ]
 [ 1.64292217  1.67822469]
 [-1.79448326 -1.1396899 ]
 [-0.45771448  0.32562569]
 [ 0.11518643 -0.03757219]
 [-0.26674751 -0.35067382]
 [-0.11821765 -1.36512307]]
[[ 2.02485611  2.12909102]
 [-2.36738416 -1.8159894 ]
 [-0.83964842 -0.68882357]]


In [135]:
# X_train, X_test의 3,4열 삭제 후, X_train_sc, X_test_sc 결합
X_train = np.delete(X_train,[3,4],axis=1)
X_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [136]:
#NaN이 포함된 ndarray의 평균 구하기
# nanmean(ndarray, axis)
np.nanmean(X[:,[1,2]],axis=0)

array([38.77777777777778, 63777.77777777778], dtype=object)

# 선형회귀 (Linear regression)